# Generated by Django 3.2.5 on 2021-07-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezo', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='productimg'),
        ),
    ]
